/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dedup;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertTrue;

import java.nio.file.Path;

import org.junit.Before;
import org.junit.Test;

public class FileChecksumTest {

    Path iconPath;

    @Before
    public void setUp() throws Exception {
        iconPath = Path.of(getClass().getResource("icons").toURI());
    }

    @Test
    public void shouldBeSameChecksum() throws Exception {
        var chk1 = FileChecksum.checksumFor(Path.of(iconPath.toString(), "uu.gif"));
        var chk2 = FileChecksum.checksumFor(Path.of(iconPath.toString(), "uuencoded.gif"));
        assertEquals(chk1, chk2);
    }

    @Test
    public void shouldBeTheSame() throws Exception {
        var file1 = Path.of(iconPath.toString(), "uu.gif");
        var file2 = Path.of(iconPath.toString(), "uuencoded.gif");
        assertTrue(FileChecksum.isSameFile(file1, file2));
    }

    @Test
    public void shouldBeDifferent() throws Exception {
        var file1 = Path.of(iconPath.toString(), "uu.gif");
        var file2 = Path.of(iconPath.toString(), "uu.png");
        assertFalse(FileChecksum.isSameFile(file1, file2));
    }

}
