/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dedup;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertThrows;

import java.io.IOException;
import java.nio.file.Path;
import java.util.Collection;
import java.util.Set;

import org.junit.Before;
import org.junit.Test;

public class HybridScannerTest {

    HybridScanner driver;

    Collection<Path> iconPath;

    @Before
    public void setUp() throws Exception {
        driver = new HybridScanner();
        iconPath = Set.of(Path.of(getClass().getResource("icons").toURI()));
    }

    @Test
    public void shouldFindDuplicatesUsingThreading() throws Exception {
        var res = driver.scan(iconPath);
        assertEquals(4, res.size());
    }

    @Test
    public void shouldFindDuplicatesUsingNonThreading() throws Exception {
        var res = driver.scan(iconPath);
        assertEquals(4, res.size());
    }

    @Test
    public void shouldThrowErrorOnFile() throws Exception {
        assertThrows(IOException.class, () -> {
            var icon = Set.of(Path.of(iconPath.toString(), "uu.png"));
            driver.scan(icon);
        });
    }

    @Test
    public void shouldThrowErrorOnNull() throws Exception {
        assertThrows(NullPointerException.class, () -> {
            driver.scan(null);
        });
    }

}
