/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dedup;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertThrows;

import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Collection;
import java.util.Set;
import java.util.concurrent.ConcurrentLinkedQueue;

import org.junit.Before;
import org.junit.Test;

public class ThreadedScannerTest {

    DuplicateScanner driver;

    Collection<Path> iconPath;

    @Before
    public void setUp() throws Exception {
        driver = new ThreadedScanner();
        iconPath = Set.of(Path.of(getClass().getResource("icons").toURI()));
    }

    @Test
    public void shouldFindDuplicates() throws Exception {
        var res = driver.scan(iconPath);
        assertEquals(4, res.size());
    }

    @Test
    public void shouldFindPotentialDuplicates() throws Exception {
        var res = driver.getPotentialDuplicates(iconPath, new ConcurrentLinkedQueue<>());
        assertEquals(120, res.size());
    }

    @Test
    public void shouldFindNoDuplicatesGivenAFile() throws Exception {
        var folder = iconPath.iterator().next().toString();
        var res = driver.scan(Set.of(Paths.get(folder, "uu.png")));
        assertEquals(0, res.size());
    }

    @Test
    public void shouldThrowErrorOnNull() throws Exception {
        assertThrows(NullPointerException.class, () -> {
            driver.scan(null);
        });
    }

}
